### ISSUE TITLE
Functional issue||No OTP received for enquiry when user logs in with google

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LeleCar#11]
Steps of execution - 
1. Go to Profile > click on Login with Google. 
2. Go to Home Page > click on a Car. 
3. Click on the call or chat option. 
4. No OTP received for the same server. 

PFA to the screenshot attached for reference - 
https://screenrec.com/share/JEWSvoLcs8

**Comment by DestekNamrata** [comment]
Resolved,and for sms part ,it will be sent to dealer number

**Comment by Tejashri-23** [comment]
Closed
