### ISSUE TITLE
Functional issue||Register as a new user|| Does not request for OTP

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LeleCar#15]
PFA to the steps of execution - 
1. Go to side menu > Profile page. 
2. Click on the "sign up" option on Profile Page.
3. Enter the username, email and password - click on sign up.
4. Verify account.
5. Click on the side menu>Home Page>select a car.
6. On selection > click on "Call" button. 
7. No OTP is received for verification. 

PFA to the screenshot attached for reference - 
https://screenrec.com/share/lu6bSct0pB

**Comment by DestekNamrata** [comment]
Resolved

**Comment by Tejashri-23** [comment]
Closed.
