### ISSUE TITLE
Functional issue||User can post free ad without login||To be discussed

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LeleCar#5]
Steps of execution -
1. Click on "Post free ad".
2. Click on the upload pic placeholder. 
3. Select a picture.
4. Enter the mandatory details and click on the post free ad. 
5. Shows "success" to post a free ads.

**Comment by DestekNamrata** [comment]
Resolved

**Comment by Tejashri-23** [comment]
closed as resolved
