### ISSUE TITLE
Suggestion||SMS received||Signin with OTP|| Post login SMS received

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LeleCar#8]
PFA to the steps of execution - 
1. Go to Profile > click on "sign in with OTP.
2. Click on sign in with OTP.
3. Once the user is logged in with OTP, sign in with OTP. 
4. An SMS is received on the mobile device with which the user has logged in. 

The message shows as a "Test" message. Please update the message with the actual message required. 
PFA to the screenshot attached - 
https://screenrec.com/share/j1u3dakHsK

**Comment by DestekNamrata** [comment]
Resolved

**Comment by Tejashri-23** [comment]
SMS service removed. Closed
